version: 0.0
os: linux

files:
  - source: /awspipelinedemo.war
    destination: /opt/apache-tomcat-8.5.70/webapps
  - source: /TestXMLFile.xml
    destination: /opt/apache-tomcat-8.5.70/webapps
    
hooks:
  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root 
